### ISSUE TITLE
Testing with Flutter Driver

### ISSUE THREAD

**Issue by themightychris** [BlinkID/blinkid-flutter#13]
Does the BlinkID development team have any experience / guidance to offer for users that want to build flutter_driver integration tests that go through BlinkID scans?

We're picturing something where we have a set of test ID photos (can BlinkID provide any?) that our flutter_driver tests can push into the android emulator via ADB commands (we already have success calling `adb` from our integration tests to extend flutter_driver capabilities) so that our flutter_driver tests can go through workflows as true-to-use as possible, providing a photo to the emulator and getting back a normal scan result when it comes to ID scan steps

**Comment by dCubelic** [comment]
Hi, @themightychris 

we do not have any experience using integration tests on flutter so unfortunately we cannot offer you any guidance.

As far as test ID photos are concerned, you can find some samples here https://www.consilium.europa.eu/prado/en/search-by-document-country.html. Hopefully this helps you.

I am marking this issue as closed now, if there is anything else I can help you with feel free to reopen.

Best regards,
Dominik
