### ISSUE TITLE
Info.plist missing required key (IOS)

### ISSUE THREAD

**Issue by devSumanrazz** [BlinkID/blinkid-flutter#20]
Missing required key in info.plist while uploading to App Store after upgrading to 5.10.0.
<img width="747" alt="Screen Shot 2021-02-25 at 4 30 00 PM" src="https://user-images.githubusercontent.com/22029165/109155224-6bf64200-7797-11eb-911f-cbedec0545ce.png">

**Comment by juraskrlec** [comment]
Hi @devSumanrazz 

Please follow [this guide](https://github.com/BlinkID/blinkid-ios#-missing-cfbundleversion-and-cfbundleshortversionstring) for a workaround. We are sorry for inconvenience, this will be fixed immediately for the next release.

**Comment by anjapenic** [comment]
Hello @devSumanrazz, 

Just wanted to let you know that this issue was fixed in v5.11.0, so we're closing this issue. If you need any further assistance, feel free to contact us at support@microblink.com or open an issue here.

Best regards,
Anja
