### ISSUE TITLE
Type of the document returns Types.None for passports

### ISSUE THREAD

**Issue by mehulcs** [BlinkID/blinkid-flutter#24]
Library is able to scan the passports and parse the result, But the type of the document always returns `Types.None` for passport documents. For the driver's license, the type is returned correctly.

I'm reading the type from below field,
`result.classInfo.type`

I have scanned passports of the below countries, But none of them returns the type.

```
Spain
German
India
Australia
Ireland
New Zealand
USA
Canada
China
```

Thanks.

_Originally posted by @mehulcs in https://github.com/BlinkID/blinkid-flutter/issues/23#issuecomment-833436900_

**Comment by anjapenic** [comment]
Hi @mehulcs,

Could you share with us the exact code snippet you're using to get the document type from the results?

Also, are you scanning real passports or fake samples?

Regards,
Anja

**Comment by anjapenic** [comment]
Hi @mehulcs,

One more thing, which SDK version are you using? We've only added support for returning the document type through ClassInfo for IDs, Visas and Passports in v5.10.0 (https://github.com/BlinkID/blinkid-android/releases/tag/v5.10.0).

Regards,
Anja

**Comment by mehulcs** [comment]
Hi @anjapenic , Thank you very for responding.

I use the `classInfo` key from the result object. 

```
result[0].classInfo.type
```

I'm not using real passports for scanning, Those are just digital images. But this works for the license documents. Only passports return the type `Types.None`.

I'm using `blinkid_flutter: ^5.8.1` of the package.

Thanks,
Mehul

**Comment by anjapenic** [comment]
Hi @mehulcs,

The reason for not getting document type is because you're using an older version of the SDK, in order to use ClassInfo to get document type you will have to use at least v5.10.0, but it would be best to update to the latest version - v5.11.0. 

Please try updating to the latest version and let us know if it helped. If you have any further questions feel free to ask.

Best regards,
Anja

**Comment by mehulcs** [comment]
Hi @anjapenic 

The latest version `5.11.0` worked.

Thanks.
