### ISSUE TITLE
Implementation for ios : not found object signResult, digitalSignature and digitalSignatureVersion

### ISSUE THREAD

**Issue by mohachouch** [BlinkID/blinkid-flutter#30]
Hello,

I try Blink on ios with flutter but I have the following errors :

[/Users/mohamedchouchane/.pub-cache/hosted/pub.dartlang.org/blinkid_flutter-5.15.1/ios/Classes/MicroblinkModule/Recognizers/Wrappers/MBUsdlCombinedRecognizerWrapper.m:46:24](): error: property 'signResult' not found on object of type 'MBUsdlCombinedRecognizer *'
    [/Users/mohamedchouchane/.pub-cache/hosted/pub.dartlang.org/blinkid_flutter-5.15.1/ios/Classes/MicroblinkModule/Recognizers/Wrappers/MBUsdlCombinedRecognizerWrapper.m:74:39](): error: property 'digitalSignature' not found on object of type 'MBUsdlCombinedRecognizerResult *'
    [/Users/mohamedchouchane/.pub-cache/hosted/pub.dartlang.org/blinkid_flutter-5.15.1/ios/Classes/MicroblinkModule/Recognizers/Wrappers/MBUsdlCombinedRecognizerWrapper.m:75:74](): error: property 'digitalSignatureVersion' not found on object of type 'MBUsdlCombinedRecognizerResult *'

Thanks for your assistance

**Comment by mparadina** [comment]
Hi @mohachouch 

Would you mind sharing the steps on how did you reproduce the mentioned exception?

Was the issue reproduced with our sample application, or when you tried to integrate the plugin into your project?
Also, was the issue reproduced with the current latest version (v5.15)?

Regards,
Milan

**Comment by mohachouch** [comment]
Thanks for your response : 

I integrated the tool in my application.

I use the following versions:

iOS Target 13
flutter 2.8.1
blinkid_flutter 5.15.1

Thanks

**Comment by mohachouch** [comment]
The error is because of the new version 5.15.1, I forced the version to 5.15.0 and the compilation is ok.

![image](https://user-images.githubusercontent.com/25939826/152744813-bedd201d-6340-46a8-8038-64c134a7aca2.png)

**Comment by volvicoasis** [comment]
Hello,
v5.15.0 is retracted from pub.dev, and v5.15.1 is not compiling (see logs above). 
Remarks pretty same same symptoms as @mohachouch,
can you provide support, we can't build our product anymore. I precise that we have a valid licence (p42 company).
We need last version wich include last id cards.

[error.txt](https://github.com/BlinkID/blinkid-flutter/files/8026802/error.txt)


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.2 20G95 darwin-x64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)

**Comment by mohachouch** [comment]
@volvicoasis You can force the version of blink 5.15.0 in the podspec

![image](https://user-images.githubusercontent.com/25939826/153171680-803d65a1-2dfc-49d2-b465-1e14b84b8f75.png)

**Comment by volvicoasis** [comment]
Thx dude @mohachouch , we use in our Podfile   => pod 'PPBlinkID', '5.15.0'

**Comment by anjapenic** [comment]
Hi @volvicoasis,

Just to confirm, did @mohachouch's suggested solution solve the issue?

Regards,
Anja

**Comment by anjapenic** [comment]
Hi @volvicoasis,

We've added support for the new France ID in v5.15.0, so there should be no issues with that document when using v5.15.0. If you're experiencing any issues regarding the new France ID, please let us know so we could check it out. There were no major changes between v5.15.0 and v5.15.1, we've only updated our newly rebranded logo.

We're aware of the issue with BlinkID Flutter v5.15.1 and are working towards fixing it in v5.16.0. In the meantime, please use v5.15.0 and let us know if you encounter any issues.

Best regards,
Anja

**Comment by dev4jam** [comment]
I have the same issue on both v5.15.0 and v5.15.1. Try to add and remove this plugin. Clean up the project. But still the same issue:

`
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Semantic Issue (Xcode): Property 'signResult' not found on object of type 'MBUsdlCombinedRecognizer *'
[/Users/dman/.pub-cache/hosted/pub.dartlang.org/blinkid_flutter-5.15.1/ios/Classes/MicroblinkModule/Recognizers/Wrappers/MBUsdlCombinedRecognizerWrapper.m:45:23]()

Semantic Issue (Xcode): Property 'digitalSignature' not found on object of type 'MBUsdlCombinedRecognizerResult *'
[/Users/dman/.pub-cache/hosted/pub.dartlang.org/blinkid_flutter-5.15.1/ios/Classes/MicroblinkModule/Recognizers/Wrappers/MBUsdlCombinedRecognizerWrapper.m:73:38]()

Semantic Issue (Xcode): Property 'digitalSignatureVersion' not found on object of type 'MBUsdlCombinedRecognizerResult *'
[/Users/dman/.pub-cache/hosted/pub.dartlang.org/blinkid_flutter-5.15.1/ios/Classes/MicroblinkModule/Recognizers/Wrappers/MBUsdlCombinedRecognizerWrapper.m:74:73]()
`

**Comment by mohachouch** [comment]
@dev4jam I think you update sur pub file. Force the version and the iOS podfile.
