### ISSUE TITLE
Failed to build `Android app` after adding `blinkid_flutter` to dependencies!

### ISSUE THREAD

**Issue by EhabSalah** [BlinkID/blinkid-flutter#32]
Could not resolve compiler classpath. Check if Kotlin Gradle plugin repository is configured in project ':app'.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileProductionDebugKotlin'.
> Could not resolve all dependencies for configuration ':app:kotlinCompilerClasspath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven2(http://maven.microblink.com)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.4/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Exception: Gradle task assembleProductionDebug failed with exit code 1

**Comment by anjapenic** [comment]
Hi @EhabSalah,

Thanks for reaching out and reporting this. We'll fix this in our next release - v5.16.0, which is expected by the end of the month. In the meantime, you can follow the instructions here - [https://docs.gradle.org/7.4/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol](https://docs.gradle.org/7.4/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol) to compile the app.

Best regards,
Anja

**Comment by kuhnroyal** [comment]
The workaround does not help, since the repository is declared in the blinkid plugin.
Currently unable to test or use the plugin except for manually editing the plugins build.gradle after each pub get.

**Comment by krizaa** [comment]
Hey, this is fixed in v5.18.0. Sorry for waiting a bit :) 
I'm closing this issue and if it persists, please reach out to us.
