### ISSUE TITLE
Error: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4 

### ISSUE THREAD

**Issue by Micheal1214** [BlinkID/blinkid-flutter#45]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/127172786/224266877-6474bf1a-55e0-4211-bcb6-2c9346fa0ff6.png">

hi, when I try your sample code to scan passport got this error.
I don't know what issue, can u help me? 
In version 6.1.0

**Comment by Brankacro** [comment]
Thank you @Micheal1214. We managed to reproduce the issue on our end. Once we have more info, we'll get back to you. Thanks for understanding.

**Comment by Brankacro** [comment]
Hello @Micheal1214. Just to inform you that we made a fix and a new update has been published, BlinkIDFlutter v6.1.2. Please test it out and let us know if everything goes well. Best.
