### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libBlinkID.so" not found

### ISSUE THREAD

**Issue by mzuzic-maidea** [BlinkID/blinkid-flutter#51]
I am trying to add MicroBlink id scan to the app but I am facing following error.

E/lIlIllllII.java:22@main( 7490): error loading native library
E/lIlIllllII.java:22@main( 7490): java.lang.UnsatisfiedLinkError: dlopen failed: library "libBlinkID.so" not found
E/lIlIllllII.java:22@main( 7490):       at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
E/lIlIllllII.java:22@main( 7490):       at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/lIlIllllII.java:22@main( 7490):       at java.lang.System.loadLibrary(System.java:1661)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.secured.lIlIllllII.IllIIIllII(line:9)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.hardware.MicroblinkDeviceManager.<clinit>(line:35)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.secured.lIlIllllII.IllIIIllII(line:3)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.secured.lIlIllllII.llIIlIlIIl(line:1)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.MicroblinkSDK.<clinit>(line:1)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.setLicense(BlinkIDFlutterPlugin.java:105)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.onMethodCall(BlinkIDFlutterPlugin.java:84)
E/lIlIllllII.java:22@main( 7490):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/lIlIllllII.java:22@main( 7490):       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/lIlIllllII.java:22@main( 7490):       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/lIlIllllII.java:22@main( 7490):       at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/lIlIllllII.java:22@main( 7490):       at android.os.Handler.handleCallback(Handler.java:958)
E/lIlIllllII.java:22@main( 7490):       at android.os.Handler.dispatchMessage(Handler.java:99)
E/lIlIllllII.java:22@main( 7490):       at android.os.Looper.loopOnce(Looper.java:205)
E/lIlIllllII.java:22@main( 7490):       at android.os.Looper.loop(Looper.java:294)
E/lIlIllllII.java:22@main( 7490):       at android.app.ActivityThread.main(ActivityThread.java:8177)
E/lIlIllllII.java:22@main( 7490):       at java.lang.reflect.Method.invoke(Native Method)
E/lIlIllllII.java:22@main( 7490):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/lIlIllllII.java:22@main( 7490):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/lIlIllllII.java:22@main( 7490): error loading native library
E/lIlIllllII.java:22@main( 7490): java.lang.UnsatisfiedLinkError: dlopen failed: library "libBlinkID.so" not found
E/lIlIllllII.java:22@main( 7490):       at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
E/lIlIllllII.java:22@main( 7490):       at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/lIlIllllII.java:22@main( 7490):       at java.lang.System.loadLibrary(System.java:1661)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.secured.lIlIllllII.IllIIIllII(line:9)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.secured.lIlIllllII.llIIlIlIIl(line:1)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.MicroblinkSDK.<clinit>(line:1)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.setLicense(BlinkIDFlutterPlugin.java:105)
E/lIlIllllII.java:22@main( 7490):       at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.onMethodCall(BlinkIDFlutterPlugin.java:84)
E/lIlIllllII.java:22@main( 7490):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/lIlIllllII.java:22@main( 7490):       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/lIlIllllII.java:22@main( 7490):       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/lIlIllllII.java:22@main( 7490):       at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/lIlIllllII.java:22@main( 7490):       at android.os.Handler.handleCallback(Handler.java:958)
E/lIlIllllII.java:22@main( 7490):       at android.os.Handler.dispatchMessage(Handler.java:99)
E/lIlIllllII.java:22@main( 7490):       at android.os.Looper.loopOnce(Looper.java:205)
E/lIlIllllII.java:22@main( 7490):       at android.os.Looper.loop(Looper.java:294)
E/lIlIllllII.java:22@main( 7490):       at android.app.ActivityThread.main(ActivityThread.java:8177)
E/lIlIllllII.java:22@main( 7490):       at java.lang.reflect.Method.invoke(Native Method)
E/lIlIllllII.java:22@main( 7490):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/lIlIllllII.java:22@main( 7490):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime( 7490): FATAL EXCEPTION: main
E/AndroidRuntime( 7490): Process: com.microblink.sample, PID: 7490
E/AndroidRuntime( 7490): java.lang.UnsatisfiedLinkError: dlopen failed: library "libBlinkID.so" not found
E/AndroidRuntime( 7490):        at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
E/AndroidRuntime( 7490):        at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/AndroidRuntime( 7490):        at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime( 7490):        at com.microblink.blinkid.secured.lIlIllllII.IllIIIllII(line:9)
E/AndroidRuntime( 7490):        at com.microblink.blinkid.secured.lIlIllllII.llIIlIlIIl(line:1)
E/AndroidRuntime( 7490):        at com.microblink.blinkid.MicroblinkSDK.<clinit>(line:1)
E/AndroidRuntime( 7490):        at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.setLicense(BlinkIDFlutterPlugin.java:105)
E/AndroidRuntime( 7490):        at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.onMethodCall(BlinkIDFlutterPlugin.java:84)
E/AndroidRuntime( 7490):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime( 7490):        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 7490):        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime( 7490):        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 7490):        at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 7490):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7490):        at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime( 7490):        at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime( 7490):        at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime( 7490):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7490):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 7490):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/Process ( 7490): Sending signal. PID: 7490 SIG: 9
Lost connection to device.

I have cloned the repo, ran the ./initFlutterSample.sh - cd to sample - Added blinkid_flutter to pubspec.yaml - pub get - flutter run (--debug) on device. App opens up, I press scan and App crashes with ☝️ error message. 

I have tried adding native library from blinkid-android and added it to the build.gradle as dependency (LibBlinkID.aar) but then I get DuplicateClass error message since I already have blinkid_flutter in pubspec.yaml I think.

So what am I excatly missing in your example?

**Comment by mzuzic-maidea** [comment]
PS C:\Users\mzuzic\Documents\projects\skipper4you-mobile> flutter doctor --verbose
[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)
    • Flutter version 3.13.1 on channel stable at C:\Users\mzuzic\Documents\android_sdks\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (4 weeks ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\mzuzic\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.1.3
    • Flutter plugin version 75.1.3
    • Dart plugin version 231.9161.14

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • sdk gphone x86 (mobile)      • emulator-5556 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 116.0.5845.188
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 117.0.2045.31

[√] Network resources
    • All expected network resources are available.

• No issues found!
PS C:\Users\mzuzic\Documents\projects\skipper4you-mobile>

**Comment by mzuzic-maidea** [comment]
I have now debugged on phsycal device with USB debugging and issue is not present, but rather new issue is
E/flutter ( 5118): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method scanWithCamera on channel blinkid_scanner)
E/flutter ( 5118): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter ( 5118): <asynchronous suspension>
E/flutter ( 5118): #1      MicroblinkScanner.scanWithCamera (package:blinkid_flutter/microblink_scanner.dart:26:34)
E/flutter ( 5118): <asynchronous suspension>
E/flutter ( 5118): #2      _AppPageState.scan (package:skipper4you/screens/app.dart:72:17)
E/flutter ( 5118): <asynchronous suspension>
E/flutter ( 5118): 
W/per4you.crew.v3( 5118): Cleared Reference was only reachable from finalizer (only reported once)

But still in virtual device I get ☝️ error

**Comment by MBrizic01** [comment]
Hi @mzuzic-maidea, 

As you correclty noticed, you are getting the error when you are running the app on the emulator because we don't support that architecture, so this error is expected.

If you are getting the same error when running the app on a physical device, please reach out to support@microblink.com, and we will investigate this further. Thank you!

**Comment by mzuzic-maidea** [comment]
Hi, 
thank you for quick reply. I have managed to get it working on real device after several cache cleans from Android Studio, PC reboot, reinstalling several time on real device and it started working. Have no clue what was the issue in first place it didn't work on device. 

Now it is working fine, will not use emulator to test this feature.
Thank you.
