### ISSUE TITLE
[question/enhancement] Country code in ISO format 

### ISSUE THREAD

**Issue by omartinma** [BlinkID/blinkid-flutter#63]
Hi,

Currently, I'm working on getting the nationality for a scanned passport and I would like to know if possible to get those in ISO format.

This would be beneficial since the result String would not be linked to any language, and ISO code is universally used for any API.

Also trying with a USA passport it gives me the wrong result on the nationality, so without that code, I can not even try to parse by String
<img width="416" alt="image" src="https://github.com/BlinkID/blinkid-flutter/assets/11978998/15d17713-761a-48ec-8fc5-0a650f241ab5">

Thanks!

**Comment by mparadina** [comment]
Hi @omartinma!

If you're interested in getting the ISO format of the nationality of the document owner, you can obtain it from the [MrzResult](https://github.com/BlinkID/blinkid-flutter/blob/master/BlinkID/lib/types.dart#L1860) class, to be more specific with the [nationality](https://github.com/BlinkID/blinkid-flutter/blob/master/BlinkID/lib/types.dart#L1886), [santiziedNationality](https://github.com/BlinkID/blinkid-flutter/blob/master/BlinkID/lib/types.dart#L1942) values.

So the code to obtain it would look like this:
```
result.mrzResult.santiziedNationality;
result.mrzResult.nationality;
```

Let me know if this helped.

**Comment by omartinma** [comment]
@mparadina great, that will help for Nationality and Issuing Country of the passport. What about place of birth? Thanks!

**Comment by mparadina** [comment]
Hi @omartinma 

Just wanted to check in to see if the issue can be closed?

**Comment by mparadina** [comment]
@omartinma closing the issue as it is inactive.
Feel free to reopen it if anything comes up!

**Comment by omartinma** [comment]
@mparadina sorry, i was pending on this [issue](https://github.com/BlinkID/blinkid-flutter/issues/62) and now i am coming back to this feature.

So for example in the case of California, will it return the country code associated?
