### ISSUE TITLE
Unable to Customize 'Network Error' Dialog Text

### ISSUE THREAD

**Issue by radivojeostojic** [BlinkID/blinkid-flutter#71]
Currently, when I'm on the scanning screen and there is no internet connection, a generic native dialog with the title 'Network error' is displayed. Is there a way to customize this text to something else?

<img width="374" alt="Screenshot 2024-09-11 at 20 19 36" src="https://github.com/user-attachments/assets/a11cdfed-8ec8-4b07-8b50-607caf9989b7">

**Comment by radivojeostojic** [comment]
Hey @mparadina , thanks for the reply. I was able to change the text for Android using strings.xml, but I haven't found a way to do this on iOS yet. Do you happen to know where I should look or how to make the change?

**Comment by mparadina** [comment]
Hi @radivojeostojic
Of course, glad I could help!

For iOS, you can directly change the .strings file inside the BlinkID.xcframework. 
For example, for English, you can change the [en.strings](https://github.com/BlinkID/blinkid-ios/blob/master/BlinkID.xcframework/ios-arm64/BlinkID.framework/en.strings#L82) file.

You can also override the strings by following the guide [here](https://github.com/BlinkID/blinkid-ios?tab=readme-ov-file#-localization).

Let me know if you have any additional questions.

**Comment by radivojeostojic** [comment]
Thanks for the help, I am closing this issue because now.
